### ISSUE TITLE
Windows Phone 8 / 8.1support

### ISSUE THREAD

**Issue by writeosahon** [yoik/cordova-yoik-screenorientation#35]
@gbenvenuti Nice plugin! This is exactly when I've been searching for!! 
I would like to know any plans on implementing this plugin for Windows Phone? I need it for a project and I'm working on. Besides Windows Phone is considered as one of the 3 major platforms :)

Awaiting any feedback on this.
Thanks

**Comment by gbenvenuti** [comment]
WP8 support added in 1.3.4
