### ISSUE TITLE
Explain more to install this plugin

### ISSUE THREAD

**Issue by robochris** [yoik/cordova-yoik-screenorientation#43]
Can you explain more on how to install this plugin. Then just saying 
"cordova plugin add net.yoik.cordova.plugins.screenorientation"
Im new at this and it would be cool if i new how to install this because i have no clue  on what your saying.

**Comment by gbenvenuti** [comment]
It is not explained in detail as all plugins are installed the same way.  Please see the "Add Plugin Features" section in the cordova docs.

https://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html
