### ISSUE TITLE
When locking for portrait while in landscape mode, orientation doesn't change to portrait.

### ISSUE THREAD

**Issue by dpatil-gmcs** [yoik/cordova-yoik-screenorientation#44]
Thank you very much for you plugin!! It works great!!

But I have following issue on iOS :
1. App is locked to portrait mode.
2. Image is displayed on a view along with content. When image is tapped, it opens in full view. While opening image, I unlock the mode so that image can be rotated properly.
3. When image is again tapped, image is closed. While closing I lock the orientation to Portrait.
4. This all looks fine
5. When image is in LANDSCAPE mode and closed, app is locked to portrait mode but orientation still remains LANDSCAPE. When user change to Portrait mode. Then it gets locked.

When we lock orientation, app should have same orientation forcefully. 

Could you please have a look at this issue? If you can, then that will be great help.

**Comment by dpatil-gmcs** [comment]
We need this fix to go ahead with launch. Could you please let me know cost and timeline for the fix?

If you can provide fix, then that will be great help!!

**Comment by gbenvenuti** [comment]
hi @dpatil-gmcs I'm sorry but I'm not sure what you're actually saying the issue is.

If you would like me to look further please provide a test html file (inline js is fine) that demonstrates the issue.  With that I may be able to find a solution.

**Comment by dpatil-gmcs** [comment]
Hi @gbenvenuti ,

Thank you very much for your reply!!

We are developing app using KENDO UI. We have following plugins installed: 

com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
com.phonegap.plugins.mapkit 0.9.2 "MapKit"
de.appplant.cordova.plugin.badge 0.6.1 "Badge"
net.yoik.cordova.plugins.screenorientation 1.3.2 "Screen Orientation"
org.apache.cordova.camera 0.3.6 "Camera"
org.apache.cordova.device 0.2.10 "Device"
org.apache.cordova.dialogs 0.2.7 "Notification"
org.apache.cordova.file 1.1.0 "File"
org.apache.cordova.file-transfer 0.4.3 "File Transfer"
org.apache.cordova.geolocation 0.3.10 "Geolocation"
org.apache.cordova.inappbrowser 0.4.0 "InAppBrowser"
org.apache.cordova.media 0.2.11 "Media"
org.apache.cordova.splashscreen 0.3.0 "Splashscreen":

App gets locked into PORTRAIT-PRIMARY. After first unlock, we see following error in the output of the XCODE : 

2015-03-31 17:40:50.408 LakeWire[718:173528] CDVPlugin class YoikScreenOrientation (pluginName: YoikScreenOrientation) does not exist.
2015-03-31 17:40:50.409 LakeWire[718:173528] ERROR: Plugin 'YoikScreenOrientation' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2015-03-31 17:40:50.410 LakeWire[718:173528] -[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
  "YoikScreenOrientation1469035447",
  "YoikScreenOrientation",
  "screenOrientation",
  [
    "set",
    "portrait-primary"
  ]
]

Following are steps to reproduce the issue:
1. App is locked to portrait mode.
2. Image is displayed on a view along with content. When image is tapped, it opens in full view. While opening image, I unlock the mode so that image can be rotated properly.
3. When image is again tapped, image is closed. While closing I lock the orientation to Portrait.
4. This all looks fine
5. When image is in LANDSCAPE mode and closed, app is locked to portrait mode but orientation still remains LANDSCAPE. When user change to Portrait mode. Then it gets locked.

We deleted all plugins and just installed your plugin, but still we see same issue.

Please let me know if you need anything else.

Thank you in advance.

**Comment by gbenvenuti** [comment]
Hi @dpatil-gmcs, sorry if I wasn't clear last time, but you will need to provide a test case where the problem is demonstrated.  I don't have time to piece together your points and "try" and replicate the issue.

If you can provide a working html/js file(s) I can load this into a cordova project and investigate for you.

**Comment by dpatil-gmcs** [comment]
@gbenvenuti 

Thank you very much for you help!!

We were able to resolve the issue using comment by "@almarin" on the link https://github.com/yoik/cordova-yoik-screenorientation/issues/25#issuecomment-58029527

We just had to add the YoikScreenOrientation.m in Build phases -> Compile Sources.

Thank you very much for your replies and plugin!!!

**Comment by gbenvenuti** [comment]
No problem @dpatil-gmcs.  I had that happen on one project I was working on, I'm not sure why it happens sometimes...
