### ISSUE TITLE
How can I make it work on Ionic / IOS?

### ISSUE THREAD

**Issue by bernier** [yoik/cordova-yoik-screenorientation#47]
Hello,
I'm using Ionic for an IOS app.
I installed the plugin, I can rotate my app but I would like to lock the rotation on certain views (like the Login view). 

The following code gives me the error "undefined is not a function"

myApp.controller('LoginCtrl', function($scope) {
  screen.lockOrientation('portrait');
});

I tried to place the code inside

icMobileApp.run(function($ionicPlatform, $window, $rootScope) {
  $ionicPlatform.ready(function() {
    screen.lockOrientation('portrait');
  });
});

but it isn't working.

Please help.
Thank you!

**Comment by gbenvenuti** [comment]
Have you tried inside deviceready?

**Comment by bernier** [comment]
Yes, this is what I was explaining with

icMobileApp.run(function($ionicPlatform, $window, $rootScope) {
$ionicPlatform.ready(function() {
screen.lockOrientation('portrait');
});
});

**Comment by bernier** [comment]
I was able to make it work with
window.screen.lockOrientation('portrait');

thanks for the plugin!
