### ISSUE TITLE
which js files to use

### ISSUE THREAD

**Issue by m-menon** [yoik/cordova-yoik-screenorientation#48]
hi,

Firstly thanks a ton for the useful plugin. I am new to java and javascript and trying to use your plugin. I was wondering if I should use both these files: screenorientation.js and screenorientation.android.js or only one of them. I just need this to run on Android.

Thanks,
M&M

**Comment by gbenvenuti** [comment]
Hi M&M,

You don't have to specifically include any files installing the plugin will take care of that for you, cordova will load the files.

Simply run:
    
    cordova plugin add net.yoik.cordova.plugins.screenorientation

**Comment by m-menon** [comment]
hi,

Okie...thanks :-)

Cheers,
M&M
