### ISSUE TITLE
Windows Phone Support Provided

### ISSUE THREAD

**Issue by writeosahon** [yoik/cordova-yoik-screenorientation#50]
Hello @gbenvenuti . A pull request has been created which finally provides Windows Phone support for this plugin. The pull request is here: https://github.com/yoik/cordova-yoik-screenorientation/pull/49 

Please can you accept the pull request and also update the plugin on cordova registry. 
This will enable people use the plugin through phonegap build etc.

Thanks so much

**Comment by writeosahon** [comment]
Hello @gbenvenuti  . Please can you perform the merge on the above-mentioned pull request. My current project depends on it and it's urgent.

Thanks

**Comment by gbenvenuti** [comment]
Hi @writeosahon,

This has been published as 1.3.4.

**Comment by writeosahon** [comment]
@gbenvenuti Thank you for this. 
You are a life-saver!!

Thanks
